version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3307/vaishali?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3307"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: vaishali
      MYSQL_USER: rajan
      MYSQL_PASSWORD: rajan
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    volumes:
      - mysql-data:/var/lib/mysql
networks:
  springapimysql-net:
volumes:
  mysql-data: